default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: icflix_app_development
test:
  <<: *default
  database: icflix_app_test
production:
  <<: *default
  database: icflix_app_production
  username: icflix_app
  password: <%= ENV['ICFLIX_APP_DATABASE_PASSWORD'] %>
